### ISSUE TITLE
SD Update not finding "KDiffusionSampler"

### ISSUE THREAD

**Issue by Leothelion996** [AlUlkesh/sd_save_intermediate_images#21]
I was able to use this yesterday but after today's update in Stable diffusion, I'm getting some error. 

`Error loading script: sd_save_intermediate_images.py
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\stable-diffusion-webui\extensions\sd_save_intermediate_images\scripts\sd_save_intermediate_images.py", line 10, in <module>
    from modules.sd_samplers import KDiffusionSampler, sample_to_image
ImportError: cannot import name 'KDiffusionSampler' from 'modules.sd_samplers' (G:\stable-diffusion-webui\modules\sd_samplers.py)`

**Comment by AlUlkesh** [comment]
Yes, there was a big change in the webui code. This should however already been fixed with #20. Did you try the latest commit of this extension?

**Comment by Leothelion996** [comment]
Yes, I just pulled the latest version and it is working again.
