### ISSUE TITLE
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr

### ISSUE THREAD

**Issue by lhucklen** [AlUlkesh/sd_save_intermediate_images#6]
getting this error

AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr

full traceback

Error completing request
Arguments: (1, 'taco', '', 'None', 'None', None, {'image': <PIL.Image.Image image mode=RGBA size=512x512 at 0x232FD951D20>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=512x512 at 0x232FD953160>}, None, None, None, 0, 40, 4, 4, 0, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', 0, 0, 0, 0, 0, 0.25, True, 'Denoised', 5.0, 0.0, 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, False, 0, True, 384, 384, False, 2, True, True, False, False) {}
Traceback (most recent call last):
  File "C:\SDauto\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\SDauto\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\SDauto\stable-diffusion-webui\modules\img2img.py", line 152, in img2img
    processed = process_images(p)
  File "C:\SDauto\stable-diffusion-webui\modules\processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "C:\SDauto\stable-diffusion-webui\modules\processing.py", line 608, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\SDauto\stable-diffusion-webui\modules\processing.py", line 989, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "C:\SDauto\stable-diffusion-webui\modules\sd_samplers.py", line 511, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args={
  File "C:\SDauto\stable-diffusion-webui\modules\sd_samplers.py", line 440, in launch_sampling
    return func()
  File "C:\SDauto\stable-diffusion-webui\modules\sd_samplers.py", line 511, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args={
  File "C:\SDauto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\SDauto\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 521, in sample_dpmpp_2s_ancestral
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "C:\SDauto\stable-diffusion-webui\extensions\sd_save_intermediate_images\scripts\sd_save_intermediate_images.py", line 100, in callback_state
    if p.enable_hr:
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr'

**Comment by AlUlkesh** [comment]
Thanks. I suspect that has to do with the recent hires-fix changes... I'll look into it.

**Comment by AlUlkesh** [comment]
Should work now on the latest commit.
